version: '3.9'

services:
  backend-api:
    build: ./backend-api
    container_name: backend-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend-api:/app
    working_dir: /app
    networks:
      - app-network

  flutter-dev:
    build: .
    container_name: flutter-dev
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - .:/app
      - /dev/bus/usb:/dev/bus/usb
    working_dir: /app
    networks:
      - app-network
    depends_on:
      - backend-api

networks:
  app-network:
    driver: bridge

